image: node:latest

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  image: ruby:latest
  script:
    # install dpl:
    - apt-get update -qy
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    # deploy to heroku:
    - dpl --provider=heroku --app=sandy-kedi-store --api-key=$HEROKU_API_KEY --skip_cleanup
  only:
    - master